krupkat/xpano

- xpano/algorithm/algorithm.cc
- xpano/algorithm/algorithm.h
- xpano/algorithm/stitcher_pipeline.cc
- xpano/algorithm/stitcher_pipeline.h
- xpano/gui/pano_gui.cc
Trying to solve issue #17. Returning the exit code from the backend to the frontend (i.e GUI). All tests passed.
> Return exit code in result

- .github/workflows/clang-format-check.yml
- misc/scripts/format.sh
- xpano/main.cc
> Add workflow to check clang-format

- CMakeLists.txt
- xpano/constants.h
- xpano/gui/panels/sidebar.cc
- xpano/gui/pano_gui.cc
- xpano/gui/shortcut.cc
- xpano/gui/shortcut.h
- xpano/utils/imgui_.cc
Use command key shortcuts on macos
- move the shortcut code to a separate file
> Feature macos shortcut

- .github/workflows/clang-tidy-check.yml
- .github/workflows/ubuntu.yml
- xpano/constants.h
- xpano/gui/panels/preview_pane.cc
- xpano/gui/panels/preview_pane.h
- xpano/gui/panels/thumbnail_pane.cc
- xpano/gui/panels/thumbnail_pane.h
- Smooth zooming:
- Smooth thumbnail scrolling
- Preview: https://gist.github.com/krupkat/a8888d2a945c3dbc67e48f04f7880158
> Feature smooth UI

- CMakeLists.txt
- xpano/constants.h
- xpano/main.cc
- xpano/utils/config.cc
- xpano/utils/config.h
- xpano/utils/sdl_.cc
- xpano/utils/sdl_.h
Closes #23 
Window size is now persist between launches.
Saving the current window size on app exit to `config.txt`.
> Feature persistent window size

- CMakeLists.txt
- tests/CMakeLists.txt
- tests/auto_crop_test.cc
- tests/rect_test.cc
- tests/vec_test.cc
- xpano/algorithm/algorithm.cc
- xpano/algorithm/algorithm.h
- xpano/algorithm/auto_crop.cc
- xpano/algorithm/auto_crop.h
- xpano/gui/panels/preview_pane.cc
- xpano/pipeline/stitcher_pipeline.cc
- xpano/utils/rect.h
- xpano/utils/vec.h
Added auto crop functionality
- When first enabling the crop mode the app suggests optimal cropping rectangle
- Utilizing approximate algorithm to find largest inscribed rectangle in a mask
> Feature auto crop

- tests/stitcher_pipeline_test.cc
- xpano/gui/pano_gui.cc
- xpano/pipeline/stitcher_pipeline.cc
- xpano/pipeline/stitcher_pipeline.h
- faster loading of full resolution images for stitching
- loading images in parallel
- execute the full resolution branch from tests
> Stitching speedup - parallel image loading

- xpano/gui/file_dialog.cc
> Add uppercase extensions to file dialog on non-windows

- xpano/gui/panels/bugreport_pane.cc
- xpano/gui/panels/sidebar.cc
- xpano/gui/panels/sidebar.h
- xpano/gui/pano_gui.cc
Add import buttons to the main window for quicker access:
Rewrite messages in the support window:
> Feature import buttons

- .github/workflows/build-scripts.yml
- misc/build/build-ubuntu-20.sh
- misc/build/build-ubuntu-22.sh
- misc/build/build-windows-latest.ps1
- misc/scripts/generate_build_scripts.sh
- misc/scripts/python/translate_github_action.py
Build scripts in `misc/build` are autogenerated from the github workflows by
https://github.com/krupkat/xpano/blob/main/misc/scripts/python/translate_github_action.py
This adds a workflow that runs this scripts in CI and checks that the build scripts are in sync with the workflows.
> workflow to check build script consistency

- CMakeLists.txt
- misc/build/deb-package/xpano.desktop
- misc/build/deb-package/xpano.svg
Support install to `/app` prefix
Add svg icon
Fix desktop file to pass validation
> Feature flatpak support

- xpano/gui/panels/sidebar.cc
Wrong usage of ImGui table API, this is the fix:
```
ImGui::BeginTable
ImGui::EndTable
```
->
```
if (ImGui::BeginTable) {
ImGui::EndTable
}
```
fixes #77
> Fix crash when minimizing

- xpano/constants.h
- xpano/gui/layout.cc
- xpano/gui/panels/about.cc
- xpano/gui/panels/about.h
- xpano/gui/panels/warning_pane.cc
- xpano/gui/panels/warning_pane.h
- xpano/gui/pano_gui.cc
- xpano/main.cc
- xpano/utils/imgui_.cc
- xpano/utils/imgui_.h
- xpano/version.h
- xpano/version_fmt.h
Show changelog after update + version in window title:
> Feature show changelog

- CMakeLists.txt
- misc/build/build-appimage.sh
Add script to build an AppImage.
Based on the 20.04 workflow.
#109
> Feature AppImage

- CMakeLists.txt
- misc/build/build-appimage.sh
- xpano/version.h
The previous attempt didn't work, installed too many dependencies which were conflicting.
> Simplify AppImage build

- misc/build/build-bullseye.sh
- xpano/gui/panels/sidebar.cc
- xpano/utils/opencv.h
- Add a script to build on debian bullseye (tested on chromebook linux)
- Check and ifdef old OpenCV API
> Debian bullseye support

- tests/stitcher_pipeline_test.cc
- xpano/algorithm/algorithm.cc
- xpano/algorithm/progress.h
- xpano/algorithm/stitcher.cc
- xpano/algorithm/stitcher.h
- xpano/constants.h
- xpano/gui/panels/sidebar.cc
Solves #107 
Simple check for panorama size <= 16384 to catch the worst errors.
> Bugfix check pano size

- README.md
- misc/site/index.md
- xpano/algorithm/algorithm.cc
- xpano/gui/panels/preview_pane.cc
- xpano/gui/panels/sidebar.cc
- xpano/gui/shortcut.cc
- Rename rotation to adjustment
- Update in app help + readme
- Transparent image borders
> Feature adjustments polish

- xpano/algorithm/algorithm.cc
- xpano/algorithm/options.h
- xpano/algorithm/stitcher.cc
- xpano/algorithm/stitcher.h
- xpano/constants.h
- xpano/gui/panels/sidebar.cc
This is a follow up to #107, that will also help in fixing #127.
> Make max panorama size user selectable

- .github/workflows/build-scripts.yml
- .github/workflows/clang-format-check.yml
- .github/workflows/clang-tidy-check.yml
- .github/workflows/jekyll.yml
- .github/workflows/test.yml
checkout + cache from v3 to v4
> Update github actions
