krupkat/xpano

- xpano/gui/action.h
- xpano/gui/panels/about.cc
- xpano/gui/panels/about.h
- xpano/gui/panels/preview_pane.cc
- xpano/gui/panels/sidebar.cc
- xpano/gui/panels/sidebar.h
- xpano/gui/pano_gui.cc
- xpano/gui/pano_gui.h
- xpano/main.cc
- xpano/utils/future.h
Refactor the main PanoGui class for greater readability / maintainability.
- Isolated code to free functions, so that it is obvious what is their input/output. Most notably the `ModifyPano` function
- Lines of code in PanoGui class implementation went from 310 to 228
- Replaced integer members (`selected_*`) with a struct `selection_`, where `selection_.type` is one of `kImage, kMatch, kPano`
- Replaced `info_message_` and `tooltip_message` with a single `status_message_` that can be directly passed to spdlog
> Refactor PanoGui

- CMakeLists.txt
- misc/mappings/iwyu_win.imp
- tests/CMakeLists.txt
- tests/disjoint_set_test.cc
- tests/stitcher_test.cc
- xpano/algorithm/algorithm.cc
- xpano/algorithm/algorithm.h
- xpano/algorithm/stitcher_pipeline.cc
- xpano/algorithm/stitcher_pipeline.h
- xpano/constants.h
- xpano/gui/file_dialog.cc
- xpano/gui/panels/sidebar.cc
- xpano/gui/panels/sidebar.h
- xpano/gui/pano_gui.cc
- xpano/gui/pano_gui.h
- xpano/utils/disjoint_set.cc
- xpano/utils/disjoint_set.h
- xpano/utils/text.cc
Closes #15 
Exposes two options in gui:
- matching distance: "Select how many neighboring images will be considered for panorama auto detection"
- matching threshold: "Number of keypoints that need to match in order to include the two images in a panorama"
`FindPano` algorithm switched to a generic connected components search using `DisjointSet`
> Feature search strategy

- .github/workflows/ubuntu.yml
- misc/build/build-ubuntu-22.04.sh
- xpano/algorithm/algorithm.cc
- xpano/gui/backends/sdl.cc
- xpano/gui/backends/sdl.h
- xpano/gui/pano_gui.cc
- xpano/gui/shortcut.cc
- xpano/gui/shortcut.h
- xpano/main.cc
- xpano/utils/sdl_.cc
- xpano/utils/sdl_.h
Support multi-monitor setups with different scaling on Linux.
Fractional scaling is blurry on XWayland, which is unfortunately the default with SDL apps on Ubuntu 22.04 as of now.
User can switch to Wayland by running `export SDL_VIDEODRIVER=wayland`.
Determining the size at which to load the fonts is tricky as X11 / Wayland approach scaling differently:
- Wayland works more like MacOS, with having framebuffer size > window size, however it returns unusable DPI values from https://wiki.libsdl.org/SDL_GetDisplayDPI (see the warning there), so we use the framebuffer/window size ratio instead
- X11 has framebuffer size == window size and the returned DPI values can be used to determine font size, but only until SDL 2.24.0: https://github.com/libsdl-org/SDL/issues/5764
> Feature linux scaling

- CMakeLists.txt
- xpano/main.cc
- xpano/utils/imgui_.cc
- xpano/utils/imgui_.h
- xpano/utils/resource.cc
- xpano/utils/resource.h
- xpano/utils/sdl_.cc
- xpano/utils/sdl_.h
- xpano/utils/text.cc
- xpano/utils/text.h
Use [SDL_GetBasePath](https://wiki.libsdl.org/SDL_GetBasePath) instead of `argv[0]`, which didn't work after `sudo make install`.
Also put asset files to share/xpano instead of share, to better support `sudo make install`
> Fix asset loading when the exe is run from PATH

- tests/stitcher_pipeline_test.cc
- xpano/algorithm/image.cc
- xpano/algorithm/image.h
- xpano/algorithm/stitcher_pipeline.cc
- xpano/algorithm/stitcher_pipeline.h
- xpano/constants.h
- xpano/gui/panels/sidebar.cc
- xpano/gui/panels/sidebar.h
- xpano/gui/panels/thumbnail_pane.cc
- xpano/gui/pano_gui.cc
- xpano/gui/pano_gui.h
- xpano/utils/sdl_.cc
Progress in #24 
Added option to control the image preview size. 
This affects runtime / memory requirements of the loading step as keypoints / descriptors are computed over the preview images.
Preview size - size of the preview image's longer side in pixels
- decrease to get faster loading times
- increase to get more precision for panorama detection
> Feature loading parameters

- .gitignore
- CMakeLists.txt
- xpano/constants.h
- xpano/gui/action.h
- xpano/gui/panels/bugreport_pane.cc
- xpano/gui/panels/bugreport_pane.h
- xpano/gui/panels/sidebar.cc
- xpano/gui/pano_gui.cc
- xpano/gui/pano_gui.h
- xpano/log/logger.cc
- xpano/log/logger.h
Please review and let me know, thank you!
> #51 bug report window

- xpano/algorithm/algorithm.cc
- xpano/algorithm/algorithm.h
- xpano/gui/panels/sidebar.cc
- xpano/gui/panels/sidebar.h
- xpano/gui/pano_gui.cc
- xpano/gui/pano_gui.h
- xpano/pipeline/stitcher_pipeline.cc
- xpano/pipeline/stitcher_pipeline.h
1) Make [SIFT](https://docs.opencv.org/4.x/d7/d60/classcv_1_1SIFT.html) the default algorithm in the panorama stitching
- This is already the case for panorama detection, so this change makes the app behave consistently
2) In debug mode, the algorithm can be switched to default [ORB](https://docs.opencv.org/3.4/db/d95/classcv_1_1ORB.html) behavior
3) Refactor of StitchOptions, so that more stitching options can be controlled through the GUI, this advances #18 
Fixes #64
> SIFT by default in the stitch algorithm

- xpano/gui/action.h
- xpano/gui/panels/sidebar.cc
- xpano/gui/pano_gui.cc
Add an `std::variant extra` field to `Action` objects for passing extra data.
- only scroll to a pano if selecting it from the menu
- do not autoscroll if recomputing due to options change / adding or removing images, the scrolling was confusing
Small fixes
- correctly autoscroll to the first found pano
- fix for disabled chroma subsampling options
> Feature extra data in Action

- .clang-format
- .gitmodules
- CMakeLists.txt
- misc/scripts/download-submodules.sh
- xpano/gui/file_dialog.cc
- xpano/gui/file_dialog.h
- xpano/gui/panels/warning_pane.cc
- xpano/gui/panels/warning_pane.h
- xpano/gui/pano_gui.cc
- xpano/utils/expected.h
Fixes #71 
Related bug: https://github.com/btzy/nativefiledialog-extended/issues/91
- Moving nativefiledialog-extended to 1.0.3 which warns when the user has xdg-desktop-portal that doesn't support picking a directory.
- Added [tl::expected](https://github.com/TartanLlama/expected), should switch to [std::expected](https://en.cppreference.com/w/cpp/utility/expected) with C++23.
- Better error handling in `file_dialog.cc`, more user warnings, e.g. when trying to save a file in an unsupported format.
> File picker error handling

- CMakeLists.txt
- tests/CMakeLists.txt
- tests/stitcher_pipeline_test.cc
- xpano/gui/panels/sidebar.cc
- xpano/pipeline/options.h
- xpano/pipeline/stitcher_pipeline.cc
- xpano/utils/exiv2.cc
- xpano/utils/exiv2.h
We cannot build with exiv2 on launchpad for now as the required 0.28.0 version is not yet available in the packages:
- https://packages.ubuntu.com/search?keywords=libexiv2-dev
Added info in the app about supported versions:
> Make exiv2 dependency optional

- .clang-format
- .clang-tidy
- .github/workflows/test.yml
- .gitmodules
- CMakeLists.txt
- README.md
- misc/build/build-ubuntu-20.sh
- misc/build/build-windows-latest.ps1
- misc/site/index.md
- tests/CMakeLists.txt
- tests/stitcher_pipeline_test.cc
- xpano/algorithm/algorithm.cc
- xpano/algorithm/algorithm.h
- xpano/algorithm/multiblend.cc
- xpano/algorithm/multiblend.h
- xpano/algorithm/options.cc
- xpano/algorithm/options.h
- xpano/cli/signal.h
- xpano/gui/panels/sidebar.cc
- xpano/log/logger.cc
- xpano/log/logger.h
- xpano/pipeline/stitcher_pipeline.cc
- xpano/pipeline/stitcher_pipeline.h
- xpano/utils/threadpool.h
Integrating https://horman.net/multiblend/ as a blending option:
Using this fork: https://github.com/krupkat/multiblend/ as a submodule.
Compared with the [OpenCV implementation](https://docs.opencv.org/4.x/d5/d4b/classcv_1_1detail_1_1MultiBandBlender.html) Multiblend produces better image detail and smoother transitions of images with different exposure.
OpenCV has better seam estimation (using graph cuts). It is potentially doable to pass the OpenCV masks to Multiblend.
Keeping the OpenCV version as the default for now.
Fixes #76
> Feature multiblend

- README.md
- misc/build/build-macos-12.sh
- misc/scripts/python/translate_github_action.py
> docs(README): note Homebrew is required on macOS

- tests/stitcher_pipeline_test.cc
- xpano/algorithm/algorithm.cc
- xpano/algorithm/multiblend.cc
- xpano/algorithm/multiblend.h
- xpano/algorithm/options.cc
- xpano/algorithm/options.h
- xpano/gui/panels/sidebar.cc
- xpano/pipeline/options.h
Add "Multiblend (with alpha)" blending option.
- this way multiblend uses the OpenCV optimized seams
Without optimized seams:
With optimized seams:
Images credit: @sguyader
> Feature multiblend with alpha

- .clang-tidy
- .gitmodules
- CMakeLists.txt
- README.md
- misc/site/index.md
- xpano/algorithm/options.h
- xpano/pipeline/options.h
Use Multiblend with https://github.com/krupkat/multiblend/pull/25 to enable running on ARM and other non-x86 architectures.
e.g. on apple sillicon machines Xpano should build with the default build script:
```
misc/build/build-macos-12.sh
```
To get a speedup on ARM, modify the build script like this:
```diff
diff --git a/misc/build/build-macos-12.sh b/misc/build/build-macos-12.sh
index cdb6426..d9fd445 100755
--- a/misc/build/build-macos-12.sh
+++ b/misc/build/build-macos-12.sh
@@ -36,7 +36,8 @@ cmake -B build \
-DBUILD_TESTING=ON \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
-DOpenCV_DIR=opencv/install/lib/cmake/opencv4 \
-  -Dexiv2_DIR=exiv2/install/lib/cmake/exiv2
+  -Dexiv2_DIR=exiv2/install/lib/cmake/exiv2 \
+  -DMULTIBLEND_ARM_OPTIMIZED=ON
cmake --build build -j $(nproc) --target install …
```
> Feature Multiblend on ARM

- xpano/algorithm/progress.cc
- xpano/algorithm/progress.h
- xpano/constants.h
- xpano/gui/panels/sidebar.cc
- xpano/pipeline/stitcher_pipeline.cc
- xpano/pipeline/stitcher_pipeline.h
Added a cancellation animation:
https://github.com/krupkat/xpano/assets/6817216/afd6b091-f776-4cec-8af5-0fd9ff7dafec
image credit: Steven from https://monarophotography.au/
Fixed StitcherPipeline queue logic, so that a cancelled task that hangs for a while doesn't block newly enqued tasks from finishing. Eventually all tasks should be fixed, so that they can hang for as little as possible (bundle adjustment mostly).
Enhances #73
> Cancellation polish

- xpano/algorithm/stitcher.cc
This was causing crashes in multiblend.
When there are large overlap between input images, then the seam optimization algorithm can decide to completely skip some images. Multiblend implementation doesn't handle this well.
Helps fix #102
> Skip compositing of a fully obscured image

- CMakeLists.txt
- tests/stitcher_pipeline_test.cc
- xpano/algorithm/algorithm.cc
- xpano/algorithm/algorithm.h
- xpano/algorithm/image.cc
- xpano/algorithm/image.h
- xpano/constants.h
- xpano/gui/panels/sidebar.cc
- xpano/gui/pano_gui.cc
- xpano/pipeline/options.h
- xpano/pipeline/stitcher_pipeline.cc
Detect image stacks from bracketing / focus stacking that shouldn't be handled by Xpano and skip them in automatic panorama detection.
> Feature detect stacks

- tests/stitcher_pipeline_test.cc
- xpano/algorithm/algorithm.cc
- xpano/algorithm/algorithm.h
- xpano/constants.h
- xpano/gui/action.h
- xpano/gui/pano_gui.cc
When the user tried to stitch images where only a subset matched, the camera saving didn't work.
- fixed by additionally saving image indices with the camera parameters
> Bugfix incomplete panos

- tests/stitcher_pipeline_test.cc
- xpano/gui/pano_gui.cc
- xpano/pipeline/stitcher_pipeline.cc
- xpano/pipeline/stitcher_pipeline.h
- xpano/utils/vec_opencv.h
When the user tried to export a cropped pano without calculating full res first, the crop was ignored.
> Fix cropped export from preview

- .github/workflows/test.yml
- misc/build/build-bullseye.sh
- misc/build/build-macos.sh
- misc/build/build-ubuntu-20.sh
- misc/build/build-ubuntu-22.sh
- misc/build/build-universal.sh
- misc/build/build-windows-latest.ps1
- xpano/version.h
To solve https://github.com/opencv/opencv/issues/25295
> Update to opencv 4.10.0

- .github/workflows/clang-format-check.yml
- misc/scripts/format.sh
- tests/stitcher_pipeline_test.cc
- tests/vec_test.cc
- xpano/algorithm/algorithm.cc
- xpano/algorithm/algorithm.h
- xpano/algorithm/options.h
- xpano/algorithm/stitcher.cc
- xpano/algorithm/stitcher.h
- xpano/constants.h
- xpano/gui/action.h
- xpano/gui/panels/preview_pane.cc
- xpano/gui/panels/sidebar.cc
- xpano/gui/panels/warning_pane.cc
- xpano/gui/panels/warning_pane.h
- xpano/gui/pano_gui.cc
- xpano/pipeline/stitcher_pipeline.cc
- xpano/utils/opencv.cc
- xpano/utils/opencv.h
- xpano/utils/vec.h
- xpano/version_fmt.h
User can limit the max pano size in MPx, with the benefit that the app will automatically shrink the panorama to the selected MPx limit. This replaces the previous behavior where the app didn't stitch a pano if it was over a set resolution limit.
Default limit is 100 MPx.
Resolves #127
> Panorama downscaling

- xpano/gui/panels/thumbnail_pane.cc
Thumbnail tooltips would crash the app
- introduced in https://github.com/krupkat/xpano/commit/16caf69139b50da4f562578a4f5fa166b5df3c8a
- https://github.com/ocornut/imgui/releases/tag/v1.91.1
> Fix thumbnail tooltip crash
